### ISSUE TITLE
getting this error when downloading

### ISSUE THREAD

**Issue by acasualmemelord** [ComputerElite/Oculus-downgrader#10]
[26.05.2023   10:26:33.00397] Info:          Selection of user is 1.28.0_4124308878
[26.05.2023   10:26:33.00399] Info:          Asking if user wants to download Version: 1.28.0_4124308878 (5425534454212956)
[26.05.2023   10:26:33.00399] Info:          Changelog: 
[26.05.2023   10:26:34.00900] Info:          Setting selected release channel to 2017290351867153 (LIVE)
[26.05.2023   10:26:34.00901] Info:          Doing POST Request to https://graph.oculus.com/graphql with args access_token=aSecret:)&variables={"input":{"client_mutation_id":"2","app_id":"1304877726278670","release_channel_id":"2017290351867153"}}&doc_id=5380372352071467&doc=
[26.05.2023   10:26:35.00759] Info:          {"data":{"user_edit_release_channel_settings":{"application":{"__typename":"Application","id":"1304877726278670","__isAppStoreItem":"Application","comfort_tags":{"nodes":[]},"developer_privacy_policy_url":"https:\/\/beatsaber.com\/doc\/privacypolicy.txt","developer_terms_of_service_url":"http:\/\/beatsaber.com\/doc\/eula.txt","display_name":"Beat Saber","supported_player_modes":["STANDING","ROOM_SCALE"],"publisher_name":"Beat Games","supported_in_app_languages":[{"name":"English"},{"name":"French (France)"},{"name":"German"},{"name":"Japanese"},{"name":"Korean"},{"name":"Spanish (Argentina)"},{"name":"Spanish (Chile)"},{"name":"Spanish (Colombia)"},{"name":"Spanish (Mexico)"},{"name":"Spanish (Peru)"},{"name":"Spanish (Puerto Rico)"},{"name":"Spanish (Venezuela)"}],"supported_hmd_platforms":["RIFT","LAGUNA"],"supported_input_device_names":["Touch Controllers"],"user_interaction_mode_names":["Single User","Multiplayer"],"age_rating":null,"category_name":"Games","developer_name":"Beat Games","genre_names":["Music & Rhythm","Casual"],"iarc_cert":{"iarc_rating":{"id":"762062044780968"},"id":"762062031447636"},"is_360_sensor_setup_required":false,"is_concept":false,"latest_supported_binary":{"__typename":"PCBinary","version":"1.30.0_4936302759","change_log":"","supported_hmd_types":["RIFT","LAGUNA"],"total_installed_space":"1671128957","id":"5699848430114889","required_space_adjusted":"3818612605","windows_min_spec":null,"redistributables":{"edges":[]}},"recommended_graphics":"Nvidia GTX 1060 or equivalent","recommended_memory_gb":8,"recommended_processor":"Intel Core i7 Skylake or equivalent","release_date":1525201200,"supported_tracking_modes":["FRONT_FACING"],"website_url":"http:\/\/beatsaber.com\/","current_offer":{"__typename":"AppStoreOffer","offer_type":"APPSTORE_OFFER","id":"2652704344806718","__isPurchasableOfferWithApp":"AppStoreOffer","price":{"currency":"USD","offset_amount":"2999","formatted":"$29.99"},"strikethrough_price":null,"promo_benefit":null,"end_time":0,"show_timer":false,"buy_button_captions":[{"text":"In-app purchases available"}]},"viewer_release_channel":{"id":"2017290351867153"},"live_release_channel":{"id":"2017290351867153","channel_name":"LIVE","latest_supported_binary":{"__typename":"PCBinary","id":"5699848430114889"}},"release_channels":{"count":3,"nodes":[{"channel_name":"LIVE","id":"2017290351867153","latest_supported_binary":{"__typename":"PCBinary","version":"1.30.0_4936302759","id":"5699848430114889"}},{"channel_name":"unity_beta","id":"771194907949249","latest_supported_binary":{"__typename":"PCBinary","version":"1.29.4_4821066007","id":"5659705544129178"}},{"channel_name":"legacy1.29.1_unity_ver2019.4.28f1","id":"6134633666615455","latest_supported_binary":{"__typename":"PCBinary","version":"1.29.1_4575554838","id":"5581819385251128"}}]},"user_data_disclosure_translated":"This app may access your display name, username, profile pictures, avatars and a list of followers and people you follow who also own this app.","__isItemWithComfortRating":"Application","comfort_rating":"COMFORTABLE_FOR_MOST","is_viewer_subscribed_coming_soon":false,"internet_connection":"NOT_REQUIRED","internet_connection_name":"Internet connection not required","__isItemWithHmdPlatformInformaton":"Application","supported_input_devices_list":[{"name":"Touch Controllers","tag":"OCULUS_TOUCH"}],"grouping":{"iap_items_2":{"edges":[{"cursor":"AQHRKVqNNelaLG24mFQI9K7DE82h9bbvrqgBIvMej1z6zRRHIuu5DVfkd3QL-pGfGNmxN0BciZMbvubunCCtnf9e1g"}]},"id":"1546487868739502"},"has_in_app_ads":false,"external_subscription_type":"NOT_REQUIRED","subscription_items":{"count":0,"nodes":[]},"can_viewer_purchase":true,"canonical_name":"hyperbolic-magnetism-beat-saber","is_linked_fb_account_required":false,"purchase_alerts":[{"type":"INCOMPATIBLE_PLATFORM","message":"It looks like you haven't yet set up Meta Rift, which you'll need for Beat Saber. Do you want to buy it anyway?"}],"is_granted_on_hardware_registration":false,"is_purchase_restricted":false,"viewer_subscription_details":null,"pdp_subscription_details":{"is_subscribable_from_pdp":false},"viewer_has_preorder":false,"canonicalName":"hyperbolic-magnetism-beat-saber","current_trial_offer":null,"extra_buy_box_section":{"content":"Refund Policy","link_uri":"https:\/\/www.oculus.com\/legal\/quest-rift-content-refund-policy\/"},"is_viewer_entitled":false,"baseline_offer":{"price":{"offset_amount":"2999"},"id":"2652704344806718"},"__isWishlistableItem":"Application","entry":null,"is_demo_of":null,"appName":"Beat Saber","platformOffer":null,"is_giftable":true,"current_gift_offer":{"__typename":"AppStoreOffer","id":"2652704344806718"},"available_gift_coupons":{"__typename":"ApplicationAvailableGiftCouponsConnection","nodes":[]}}}}}
[26.05.2023   10:26:35.00760] Info:          Version is already downloaded. Asking if user wants to download a second time
[26.05.2023   10:26:43.00085] Info:          Downloading manifest of 5425534454212956
[26.05.2023   10:26:43.00085] Info:          Downloading manifest
[26.05.2023   10:26:43.00089] Info:          Downloading manifest.json.zip from https://securecdn.oculus.com/binaries/download/?id=5425534454212956&access_token=&get_manifest=1 to C:\Users\Downloads\Oculus.Downgrader\apps\1304877726278670\5425534454212956\manifest.json.zip
[26.05.2023   10:26:43.00340] Info:          Error while GET request: System.Net.WebException: The remote server returned an error: (404) Not Found.
[26.05.2023   10:26:43.00340] Info:             at System.Net.HttpWebRequest.GetResponse()
[26.05.2023   10:26:43.00340] Info:             at ComputerUtils.ComputerUtils_FastFileDownloader.FileDownloader.DownloadFileInternal(String url, String savePath, Int32 numConnections) in D:\Visual Studio\ComputerUtils\ComputerUtils\ComputerUtils.FastFileDownloader.cs:line 56
[26.05.2023   10:26:43.00340] Info:          Did download succeed: True
[26.05.2023   10:26:43.00536] Crash:         An unhandled exception has occured:
[26.05.2023   10:26:43.00536] Crash:         System.IO.FileNotFoundException: Could not find file 'C:\Users\Downloads\Oculus.Downgrader\apps\1304877726278670\5425534454212956\manifest.json.zip'.
[26.05.2023   10:26:43.00536] Crash:         File name: 'C:\Users\Downloads\Oculus.Downgrader\apps\1304877726278670\5425534454212956\manifest.json.zip'
[26.05.2023   10:26:43.00536] Crash:            at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
[26.05.2023   10:26:43.00536] Crash:            at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[26.05.2023   10:26:43.00536] Crash:            at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
[26.05.2023   10:26:43.00536] Crash:            at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
[26.05.2023   10:26:43.00536] Crash:            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
[26.05.2023   10:26:43.00536] Crash:            at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
[26.05.2023   10:26:43.00536] Crash:            at System.IO.Compression.ZipFile.OpenRead(String archiveFileName)
[26.05.2023   10:26:43.00536] Crash:            at OculusGraphQLApiLib.Game.GameDownloader.DownloadManifest(String destination, String access_token, String binaryId) in D:\Visual Studio\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\GameDownloader.cs:line 114
[26.05.2023   10:26:43.00536] Crash:            at RIFT_Downgrader.DowngradeManager.Download(AndroidBinary selected, String appId, String appName) in D:\Visual Studio\RIFT Downgrader\Oculus Downgrader\Program.cs:line 1376
[26.05.2023   10:26:43.00536] Crash:            at RIFT_Downgrader.DowngradeManager.ShowVersions(String appId) in D:\Visual Studio\RIFT Downgrader\Oculus Downgrader\Program.cs:line 1326
[26.05.2023   10:26:43.00536] Crash:            at RIFT_Downgrader.DowngradeManager.Menu() in D:\Visual Studio\RIFT Downgrader\Oculus Downgrader\Program.cs:line 332
[26.05.2023   10:26:43.00536] Crash:            at RIFT_Downgrader.Program.Main(String[] args) in D:\Visual Studio\RIFT Downgrader\Oculus Downgrader\Program.cs:line 92

**Comment by ComputerElite** [comment]
It seems that you did not log in with an meta account that owns beat saber
