### ISSUE TITLE
download doesn't finish

### ISSUE THREAD

**Issue by evvaea** [ComputerElite/Oculus-downgrader#12]
these are all the exceptions, if you need more info lmk (my friend is having the issue, download worked fine for me)

[01.11.2023   02:25:37.00270] Crash:         An unhandled exception has occured:
[01.11.2023   02:25:37.00270] Crash:         System.NullReferenceException: Object reference not set to an instance of an object.
[01.11.2023   02:25:37.00270] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.DownloadNextFileFromQueue() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 48
[01.11.2023   02:25:37.00270] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.AfterFileDecompressed() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 126
[01.11.2023   02:25:37.00270] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.<>c__DisplayClass38_0.<DownloadNextFileFromQueue>b__1() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 90
[01.11.2023   02:25:37.00270] Crash:            at ComputerUtils.ComputerUtils_FastFileDownloader.FileDownloader.DownloadFileInternal(String url, String savePath, Int32 numConnections) in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\ComputerUtils\ComputerUtils\ComputerUtils.FastFileDownloader.cs:line 172
[01.11.2023   02:25:37.00270] Crash:            at ComputerUtils.ComputerUtils_FastFileDownloader.FileDownloader.<>c__DisplayClass9_0.<DownloadFile>b__0() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\ComputerUtils\ComputerUtils\ComputerUtils.FastFileDownloader.cs:line 43

[01.11.2023   02:25:43.00880] Crash:         An unhandled exception has occured:
[01.11.2023   02:25:43.00880] Crash:         System.NullReferenceException: Object reference not set to an instance of an object.
[01.11.2023   02:25:43.00880] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.DownloadNextFileFromQueue() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 48
[01.11.2023   02:25:43.00880] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.AfterFileDecompressed() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 126
[01.11.2023   02:25:43.00880] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.<>c__DisplayClass38_0.<DownloadNextFileFromQueue>b__1() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 90
[01.11.2023   02:25:43.00880] Crash:            at ComputerUtils.ComputerUtils_FastFileDownloader.FileDownloader.DownloadFileInternal(String url, String savePath, Int32 numConnections) in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\ComputerUtils\ComputerUtils\ComputerUtils.FastFileDownloader.cs:line 172
[01.11.2023   02:25:43.00880] Crash:            at ComputerUtils.ComputerUtils_FastFileDownloader.FileDownloader.<>c__DisplayClass9_0.<DownloadFile>b__0() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\ComputerUtils\ComputerUtils\ComputerUtils.FastFileDownloader.cs:line 43

[01.11.2023   02:25:53.00438] Crash:         An unhandled exception has occured:
[01.11.2023   02:25:53.00438] Crash:         System.NullReferenceException: Object reference not set to an instance of an object.
[01.11.2023   02:25:53.00438] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.DownloadNextFileFromQueue() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 48
[01.11.2023   02:25:53.00438] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.AfterFileDecompressed() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 126
[01.11.2023   02:25:53.00438] Crash:            at OculusGraphQLApiLib.Game.SegmentDownloader.<>c__DisplayClass38_0.<DownloadNextFileFromQueue>b__1() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\OculusGraphQLApiLib\OculusGraphQLApiLib\Game\SegmentDownloader.cs:line 90
[01.11.2023   02:25:53.00438] Crash:            at ComputerUtils.ComputerUtils_FastFileDownloader.FileDownloader.DownloadFileInternal(String url, String savePath, Int32 numConnections) in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\ComputerUtils\ComputerUtils\ComputerUtils.FastFileDownloader.cs:line 172
[01.11.2023   02:25:53.00438] Crash:            at ComputerUtils.ComputerUtils_FastFileDownloader.FileDownloader.<>c__DisplayClass9_0.<DownloadFile>b__0() in D:\a\Oculus-downgrader\Oculus-downgrader\OculusDB\ComputerUtils\ComputerUtils\ComputerUtils.FastFileDownloader.cs:line 43

**Comment by davidsin02** [comment]
Did they uninstall the game first before proceeding with this?

**Comment by evvaea** [comment]
> Did they uninstall the game first before proceeding with this?

yes

**Comment by ComputerElite** [comment]
Just try again usually that works after a few times

**Comment by evvaea** [comment]
we tried it ~6 times but we'll try again today 👍

**Comment by ComputerElite** [comment]
Share your complete log file then please

**Comment by evvaea** [comment]
sorry I didn't realize you could attach files, I only have 2 logs since he reinstalled it 3 times but these 2 have 4 attempts combined and the same thing was happening on all of them
[Log2.log](https://github.com/ComputerElite/Oculus-downgrader/files/13226543/Log2.log)
[Log.log](https://github.com/ComputerElite/Oculus-downgrader/files/13226544/Log.log)

**Comment by ComputerElite** [comment]
Thanks, I'll take a look at it when I get on my pc

**Comment by evvaea** [comment]
okay, thank you so much for your help! Take as much time as you need.

**Comment by ComputerElite** [comment]
Not sure if I fixed the issue but instead of crashing Oculus Downgrader *should* now just retry the download if it fails on a specific file for an unknown reason. Tell your friend to update to the most recent version (Open it -> allow it to update) and try again
