### ISSUE TITLE
Can not download rift games from command line

### ISSUE THREAD

**Issue by Aldin101** [ComputerElite/Oculus-downgrader#14]
when using the command line args to download games the following error is given
Request to OculusDB and Oculus failed. Cannot proceed with download

the command line args were
`"d -nU --token mytoken --destination "C:\Program Files\Oculus\Software\Software" --noquit --appid 1369078409873402 --versionid 6323983201049540 --headset rift"`
I have tried a lot of different orders for the arguments but nothing seems to do it. Option 11 and manually searching work fine. This is simply a bug report.

BONUS BUG 🥳
Request to Oculus failed. Requesting from OculusDB instead. OculusBB may not have every version...
OculusBD is spelled as OculusBB

**Comment by ComputerElite** [comment]
Could you try these arguments?
"d -nU --token mytoken --destination "C:\Program Files\Oculus\Software\Software" --noquit --appid 1369078409873402 --versioncode 2202 --headset rift"

**Comment by ComputerElite** [comment]
I'll look into this issue in more detail after school

**Comment by Aldin101** [comment]
Now it finds the version but is says:
Found version

Version: 34.4.631547.1 (6323983201049540)
Changelog:

Starting download
Saving version info

You need to enter your access_token again so it can be securely stored
Your access_token is needed to authenticate downloads.


An unhandled exception has occured. Check the log for more info and send it to ComputerElite for the (probably) bug to get fixed. Press any key to close out

the log:
[28.11.2023   08:59:34.00866] Crash:         An unhandled exception has occured:
[28.11.2023   08:59:34.00866] Crash:         System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
[28.11.2023   08:59:34.00866] Crash:            at System.String.Substring(Int32 startIndex, Int32 length)
[28.11.2023   08:59:34.00866] Crash:            at RIFT_Downgrader.DowngradeManager.DecryptToken() in D:\a\Oculus-downgrader\Oculus-downgrader\Oculus Downgrader\Program.cs:line 1450
[28.11.2023   08:59:34.00866] Crash:            at RIFT_Downgrader.DowngradeManager.StartDownload(AndroidBinary binary, String appId, String appName, Boolean skipDownload) in D:\a\Oculus-downgrader\Oculus-downgrader\Oculus Downgrader\Program.cs:line 1502
[28.11.2023   08:59:34.00866] Crash:            at RIFT_Downgrader.DowngradeManager.Download(AndroidBinary selected, String appId, String appName) in D:\a\Oculus-downgrader\Oculus-downgrader\Oculus Downgrader\Program.cs:line 1438
[28.11.2023   08:59:34.00866] Crash:            at RIFT_Downgrader.DowngradeManager.ShowVersions(String appId) in D:\a\Oculus-downgrader\Oculus-downgrader\Oculus Downgrader\Program.cs:line 1400
[28.11.2023   08:59:34.00866] Crash:            at RIFT_Downgrader.DowngradeManager.HandleCLIArgs() in D:\a\Oculus-downgrader\Oculus-downgrader\Oculus Downgrader\Program.cs:line 268
[28.11.2023   08:59:34.00866] Crash:            at RIFT_Downgrader.DowngradeManager.Menu() in D:\a\Oculus-downgrader\Oculus-downgrader\Oculus Downgrader\Program.cs:line 301
[28.11.2023   08:59:34.00866] Crash:            at RIFT_Downgrader.Program.Main(String[] args) in D:\a\Oculus-downgrader\Oculus-downgrader\Oculus Downgrader\Program.cs:line 89

I did get a new access token and set it, and it even says that at the top `Set token to OCASs...`
I did redownload oculus downgrader right before trying

**Comment by ComputerElite** [comment]
If you start Oculus Downgrader and use option 11 with ` d -nU --noquit --appid 1369078409873402 --versioncode 2202 --headset rift"` That works, right?

**Comment by Aldin101** [comment]
yes, that works fine, it only happens if you launch the program with those arguments. Do the startup arguments work for you? or is it just a me thing.

I also do reinstall between tests, and I had to do the login before using option 11

**Comment by ComputerElite** [comment]
Seems that I did not update the cli arguments to work properly, I'll fix that

**Comment by ComputerElite** [comment]
Could you try again with this run using the cli args? https://github.com/ComputerElite/Oculus-downgrader/actions/runs/7036573295

**Comment by ComputerElite** [comment]
Thanks for testing, I'll publish the version later

**Comment by Aldin101** [comment]
You're welcome, I was planning to use this tool for automatic downgrading of a game, but I ended up implementing oculus downgrade myself lol. But I'm glad I could help.
